export const environment = {
  production: true,
  api_url: 'https://syndemos.com/nandu_v1/api/',
  api_key:'nandu@123',
  slider_url:'slider_list/format/json',
  category_url:'categorylist/format/json',
  bestseller_url:'best_sale/format/json',
  best_sale_by_category_url:'best_sale_by_category/format/json',
  search_url:'search/format/json',
  productList_url:'productlist/format/json',
  login_url:'login',
  logo_url:'web_setting/format/json',
  customerInfo_Url:'Customer_info/format/json',
  reg_url:'Registration/format/json',
  stores_url:'find_stores/format/json',
  wishList_url:'wishlist/format/json',
  addtoCart:'Addtocart/format/json',
  removeCart:'Removecart/format/json',
  preCheckout:'Precheckout/format/json',
  stockAvailability:'variant/format/json',
  stockCount:'stock/format/json',
  applyCoupon:'Apply_coupon/format/json',
  countriesList:'country_list/format/json',
  countryDetails:'country_info/format/json',
  stateDetails:'state_list/format/json',
  customerUpdate:'user_update/format/json',
  changePassword:'user_change_password/format/json',
  customerOrders:'manage_orders/format/json'
};
